[package]
name = "wasmlib"
version = "0.1.0"
authors = ["terada <terada.yuichiro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[lib]
crate-type = ["cdylib"]
